### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by scttnlsn** [travis/rex#11]
I've been trying to get Rex up and running and ran into a few issues outlined below.  Would be curious to know if anyone is able to reproduce any of this (@travis @eethann).  If so I can submit a PR with some of the fixes that worked for me.

The first problem I encountered was while building the `api` image:

```bash
docker-compose build api
```

I got this error:

```
Building api
Step 1/10 : FROM mhart/alpine-node:9
9: Pulling from mhart/alpine-node
ff3a5c916c92: Pull complete
c77918da3c72: Pull complete
Digest: sha256:3c3f7e30beb78b26a602f12da483d4fa0132e6d2b625c3c1b752c8a8f0fbd359
Status: Downloaded newer image for mhart/alpine-node:9
 ---> bd69a82c390b
Step 2/10 : RUN mkdir /app
 ---> Running in ab7ad7157286
Removing intermediate container ab7ad7157286
 ---> 318949fd07a8
Step 3/10 : ADD . /app
 ---> 9faa43964e24
Step 4/10 : WORKDIR /app/schema
 ---> Running in f4a8e76a79f9
Removing intermediate container f4a8e76a79f9
 ---> a188d6a6149c
Step 5/10 : RUN npm install
 ---> Running in 75e88183ad34
npm WARN rex-schema@0.0.1 No repository field.

added 3 packages from 1 contributor in 0.988s
Removing intermediate container 75e88183ad34
 ---> ccfc93c50738
Step 6/10 : WORKDIR /app/ui
 ---> Running in 75cfebbf072a
Removing intermediate container 75cfebbf072a
 ---> b13ef6c833ff
Step 7/10 : RUN npm install && npm run build
 ---> Running in d4262dc27cbe
npm WARN notice [SECURITY] react-dev-utils has the following vulnerability: 1 high. Go here for more details: https://nodesecurity.io/advisories?search=react-dev-utils&version=5.0.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] webpack-dev-server has the following vulnerability: 1 high. Go here for more details: https://nodesecurity.io/advisories?search=webpack-dev-server&version=2.9.4 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end
npm WARN notice [SECURITY] url-parse has the following vulnerability: 1 high. Go here for more details: https://nodesecurity.io/advisories?search=url-parse&version=1.4.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end
npm WARN notice [SECURITY] merge has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=merge&version=1.2.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-28T17_14_07_537Z-debug.log
ERROR: Service 'api' failed to build: The command '/bin/sh -c npm install && npm run build' returned a non-zero code: 1
```

Apparently this is some issue with NPM: https://github.com/npm/npm/issues/19989

My Docker images were using the following Node and NPM versions:

```
docker run mhart/alpine-node:9 node --version
v9.11.1
```

```
docker run mhart/alpine-node:9 npm --version
5.8.0
```

By using the Node 10 base image I was able to move past this.  The Dockerfile base image becomes:

```docker
FROM mhart/alpine-node:10
```

And in order to build the native libsodium module I also had to install the following Alpine packages:

```docker
RUN apk update
RUN apk add build-base libtool autoconf automake python
```

The next issue I ran into was related to Babel compilation:

```
> rex@0.0.1 build /app/api
> npx babel src --out-dir dst

src/app.js -> dst/app.js
src/app.test.js -> dst/app.test.js
src/auth.js -> dst/auth.js
src/context.js -> dst/context.js
src/db/config.js -> dst/db/config.js
src/domain/errors.js -> dst/domain/errors.js
src/domain.js -> dst/domain.js
src/domain.test.js: Unexpected token (26:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rex@0.0.1 build: `npx babel src --out-dir dst`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rex@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

The code at position 26:32 of `src/domain.test.js` is a spread operator (`...travis`).  I don't know much about Babel configuration but some quick searching lead me to the [babel-preset-stage-0](https://www.npmjs.com/package/babel-preset-stage-0) plugin.  Installing this module and changing `.babelrc` to the following did the trick:

```json
{
  "presets": ["env", "stage-0"]
}
```

At this point all the images were building sucessfully.

I tried running `npm run docker:db:sync:force` but I got the following error:

```
> rex@0.0.1 db:sync:force /app/api
> babel-node src/scripts/sync_db.js --force

/usr/bin/node: bad option: --force
npm ERR! code ELIFECYCLE
npm ERR! errno 9
npm ERR! rex@0.0.1 db:sync:force: `babel-node src/scripts/sync_db.js --force`
npm ERR! Exit status 9
npm ERR!
npm ERR! Failed at the rex@0.0.1 db:sync:force script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I have no idea why the following solution works but changing `--force` to `-f` fixed the issue.

At this point I was able to sucessfully sync the database schema.

Running `docker-compose up` resulted in the following errors in the `api` and `ui` containers:

```
rex-api-dev |
rex-api-dev | > rex@1.0.0 api:start /app
rex-api-dev | > cd api && npm start
rex-api-dev |
rex-api-dev |
rex-api-dev | > rex@0.0.1 start /app/api
rex-api-dev | > npm run db:migrate && nodemon src/server.js --exec babel-node
rex-api-dev |
rex-api-dev |
rex-api-dev | > rex@0.0.1 db:migrate /app/api
rex-api-dev | > sequelize db:migrate
rex-api-dev |
rex-api-dev |
rex-api-dev | Sequelize CLI [Node: 10.14.0, CLI: 4.0.0, ORM: 4.38.0]
rex-api-dev |
rex-api-dev | Loaded configuration file "src/db/config.js".
rex-api-dev | Using environment "development".
rex-api-dev | Wed, 28 Nov 2018 17:03:11 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
rex-api-dev | No migrations were executed, database schema was already up to date.
rex-api-dev | [nodemon] 1.18.3
rex-api-dev | [nodemon] to restart at any time, enter `rs`
rex-api-dev | [nodemon] watching: *.*
rex-api-dev | [nodemon] starting `babel-node src/server.js`
rex-api-dev | internal/modules/cjs/loader.js:582
rex-api-dev |     throw err;
rex-api-dev |     ^
rex-api-dev |
rex-api-dev | Error: Cannot find module 'graphql-tag'
rex-api-dev |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
rex-api-dev |     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
rex-api-dev |     at Module.require (internal/modules/cjs/loader.js:636:17)
rex-api-dev |     at require (internal/modules/cjs/helpers.js:20:18)
rex-api-dev |     at Object.<anonymous> (/app/schema/schema.js:2:18)
rex-api-dev |     at Module._compile (internal/modules/cjs/loader.js:688:30)
rex-api-dev |     at loader (/app/api/node_modules/babel-register/lib/node.js:144:5)
rex-api-dev |     at Object.require.extensions.(anonymous function) [as .js] (/app/api/node_modules/babel-register/lib/node.js:154:7)
rex-api-dev |     at Module.load (internal/modules/cjs/loader.js:598:32)
rex-api-dev |     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
```

I tried added `graphql-tag` to the `api/package.json` and rebuilding the image but still get the same error.

The error in the `ui` container:

```
rex-ui-dev |
rex-ui-dev | > rex@1.0.0 ui:start /app
rex-ui-dev | > cd ui && npm start
rex-ui-dev |
rex-ui-dev |
rex-ui-dev | > rex-ui@0.1.0 start /app/ui
rex-ui-dev | > react-scripts start
rex-ui-dev |
rex-ui-dev | sh: react-scripts: not found
rex-ui-dev | npm ERR! file sh
rex-ui-dev | npm ERR! code ELIFECYCLE
rex-ui-dev | npm ERR! errno ENOENT
rex-ui-dev | npm ERR! syscall spawn
rex-ui-dev | npm ERR! rex-ui@0.1.0 start: `react-scripts start`
rex-ui-dev | npm ERR! spawn ENOENT
rex-ui-dev | npm ERR!
rex-ui-dev | npm ERR! Failed at the rex-ui@0.1.0 start script.
rex-ui-dev | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
rex-ui-dev | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
rex-ui-dev |
rex-ui-dev | npm ERR! A complete log of this run can be found in:
rex-ui-dev | npm ERR!     /root/.npm/_logs/2018-11-28T17_10_11_371Z-debug.log
rex-ui-dev | npm ERR! code ELIFECYCLE
rex-ui-dev | npm ERR! errno 1
rex-ui-dev | npm ERR! rex@1.0.0 ui:start: `cd ui && npm start`
rex-ui-dev | npm ERR! Exit status 1
rex-ui-dev | npm ERR!
rex-ui-dev | npm ERR! Failed at the rex@1.0.0 ui:start script.
rex-ui-dev | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
rex-ui-dev | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
rex-ui-dev |
rex-ui-dev | npm ERR! A complete log of this run can be found in:
rex-ui-dev | npm ERR!     /root/.npm/_logs/2018-11-28T17_10_11_382Z-debug.log
rex-ui-dev exited with code 1
```

Oddly, it looks as if `npm install` was never run inside the `ui` directory:

```
docker-compose run ui ls /app/ui/node_modules
ls: /app/ui/node_modules: No such file or directory
```

(`/app/api/node_modules` does indeed exist)

I haven't yet had time to figure out these errors.  Any suggestions?

**Comment by scttnlsn** [comment]
Another little side note:

I run a PostgreSQL database natively on my system and initially had a port conflict when trying to start the `db` container.  I ended up switching the ports in the `docker-compose.yml` file:

```yaml
db:
  ports:
    - 7070:5432
```

Perhaps some non-standard port should be the default here.

**Comment by eethann** [comment]
@scttnlsn my approach to building has been to use yarn for the API and to do the yarn link outside the docker container. The issue I had is that docker didn't mount the directory above the API dir, so it couldn't access the local ../schema package location.

**Comment by travis** [comment]
oh jeez - sorry I missed this, I've been plunking around and realized I left rex in a bad state - sorry!! I'm about to push a bunch of fixes that should fix some of these issues - PRs definitely welcome for others!

**Comment by travis** [comment]
ok - I think the issues in here should all be fixed in master - please do note the new instructions in the README. so, so sorry to have wasted your time trying to get a broken system working!

**Comment by travis** [comment]
also re: yarn, as far as I know there's not much reason to use yarn these days (https://iamturns.com/yarn-vs-npm-2018/) and `npm audit` has some major security goodness (https://blog.npmjs.org/post/173719309445/npm-audit-identify-and-fix-insecure) - I'm certainly not opposed to folks using yarn, but can't really provide any support for issues that come up with it!

I'm gonna close this issue out - feel free to

**Comment by travis** [comment]
woo hoo! I would expect `node_modules` to be missing until you run `npm install`, so it sounds like things are working as expected - I just realized I hadn't pushed the README updates that make this clear - those are pushed and this should be a lot clearer!

**Comment by scttnlsn** [comment]
@travis Oh, I see.  `npm install` used to be run from the Dockerfile but I see now you do that on the host system.  Great!  Thanks!

**Comment by travis** [comment]
yeah, exactly - the Dockerfile commands only get run very occasionally, and the modules they install get overridden anyway, so it makes more sense to do this outside.
